## 1. Understand the dataset

This notebook uses the diamonds dataset from Seaborn. Each row represents a diamond, and the goal is to predict its price using the available features such as carat, cut, color, and clarity.

In [ ]:
import pandas as pd
import seaborn as sns

# Load the dataset
df = sns.load_dataset("diamonds")
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

>Features (X) → information about the diamond                                    
Target (y)   → what we want to predict

## 2. Define features and target

- Features (X): the information used to make the prediction
- Target (y): the value we want to predict

In [ ]:
# Features = all columns except the target
X = df.drop("price", axis=1)

# Target = the value we want to predict
y = df["price"]

>X = questions/features                                                        
>y = answers/target

## Training Testing data:

In [ ]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

>80 diamonds → model learns from these

>20 diamonds → we test the model on these

In [4]:
X.head()

   carat      cut color clarity  depth  table     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0  4.34  4.35  2.75

## Initialize the model:

In [5]:
best_model = None
best_r2 = -float("inf")

## 3. Prepare categorical data

The columns such as `cut`, `color`, and `clarity` contain text values. These need to be converted into numbers before a machine-learning model can use them.

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

> These Columns are text

In [ ]:
categorical_columns = ["cut", "color", "clarity"]

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "encoding",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_columns
        )
    ],
    remainder="passthrough"
)

# 4. Build and compare regression models

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [ ]:
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42)
}

results = {}

for name, model in models.items():
    pipeline = Pipeline(
        steps=[
            ("preprocessor", preprocessor),
            ("model", model)
        ]
    )

    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = mse ** 0.5
    r2 = r2_score(y_test, y_pred)

    results[name] = {
        "R2": r2,
        "MAE": mae,
        "MSE": mse,
        "RMSE": rmse
    }

    print(f"{name}:")
    print(f"  R2  = {r2:.4f}")
    print(f"  MAE = {mae:.2f}")
    print(f"  RMSE = {rmse:.2f}")
    print()

## Train the model:

In [11]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('encoding',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['cut', 'color',
                                                   'clarity'])])),
                ('model', LinearRegression())])

## Predict:

In [12]:
y_pred = model.predict(X_test)

## Evaluate the model

### Metrics for Regression:

In [13]:
from sklearn.metrics import mean_absolute_error , mean_squared_error ,r2_score

In [14]:
mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse**0.5
r2 = r2_score(y_test, y_pred)

In [15]:
print("MAE:", mae)
print("RMSE:", rmse)
print("R2:", r2)

MAE: 737.1513665933181
RMSE: 1135.2116445190627
R2: 0.9189331350419387

## Add more models:

In [16]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression

In [17]:
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42)
}
for name, model in models.items():

    pipeline = Pipeline(
        steps=[
            ("preprocessor", preprocessor),
            ("model", model)
        ]
    )
    pipeline.fit(X_train, y_train)

    y_pred = pipeline.predict(X_test)

    r2 = r2_score(y_test, y_pred)

    print(name, ":", r2)

Linear Regression : 0.9189331350419387
Decision Tree : 0.9646956501931204
Random Forest : 0.9809753922281078

***************************

## 5. Select the best model

The model with the highest R² score on the test set is considered the best for this notebook.

In [ ]:
best_model_name = max(results, key=lambda name: results[name]["R2"])
best_model = models[best_model_name]

print("Best model:", best_model_name)
print("Best R2:", round(results[best_model_name]["R2"], 4))

*********************************

*************

## 6. Hyperparameter tuning with GridSearchCV

Now we improve the selected model by testing a few hyperparameter combinations.

In [ ]:
param_grid = {
    "model__n_estimators": [50, 100, 200],
    "model__max_depth": [5, 10, 20]
}

## Create the pipeline:

In [ ]:
from sklearn.model_selection import GridSearchCV

rf_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(random_state=42))
])

## Use GridSearchCV:

In [ ]:
grid_search = GridSearchCV(
    estimator=rf_pipeline,
    param_grid=param_grid,
    cv=5,
    scoring="r2",
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

In [22]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('encoding',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['cut',
                                                                          'color',
                                                                          'clarity'])])),
                                       ('model',
                                        RandomForestRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__max_depth': [5, 10, 20],
                         'model__n_estimators': [50, 100, 200]},
             scoring='r2')

## See the best hyperparameters

In [ ]:
print("Best parameters:", grid_search.best_params_)

{'model__max_depth': 20, 'model__n_estimators': 200}

## Get the best tuned model:

In [ ]:
best_model = grid_search.best_estimator_

## Evaluate it on the test set:

In [ ]:
y_pred = best_model.predict(X_test)
r2 = r2_score(y_test, y_pred)

print("Final test R²:", round(r2, 4))

Final R²: 0.981078576154558