# Import Libraries:

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

## Label Encoder:

In [3]:
le = LabelEncoder()
gender = ["Male","Female","Trans"]
encoded = le.fit_transform(gender)
print(encoded)

[1 0 2]

## One Hot Encoding:

In [6]:
from sklearn.preprocessing import OneHotEncoder
df = pd.DataFrame({
    "City": ["Lahore", "Karachi", "Lahore"]
})
ohe = OneHotEncoder(sparse_output=False)
encoded = ohe.fit_transform(df[["City"]])
print(encoded)

[[0. 1.]
 [1. 0.]
 [0. 1.]]

## Ordinal Encoder:

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({
    "Size":["Small","Medium","Large","Small","Medium"]
})
oe = OrdinalEncoder(categories=[["Small","Medium","Large"]])
encoded = oe.fit_transform(df[["Size"]])

array([[0.],
       [1.],
       [2.],
       [0.],
       [1.]])

## Feature Encoding in pandas:

In [9]:
import pandas as pd

df = pd.DataFrame({
    "City": ["Lahore", "Karachi", "Islamabad", "Lahore"]
})

print(df)
encoded_df = pd.get_dummies(df)

        City
0     Lahore
1    Karachi
2  Islamabad
3     Lahore

*********************************************************************************************************

# Python Library category_encoders:

In [11]:
#!pip install category_encoders

In [12]:
from category_encoders import BinaryEncoder

In [16]:
df1 = pd.DataFrame({
    "Size":["Small","Medium","Large","Small"]
})
ce = BinaryEncoder(cols=["Size"])
ce.fit_transform(df1)

   Size_0  Size_1
0       0       1
1       1       0
2       1       1
3       0       1

* # Discretization:

In [18]:
from sklearn.preprocessing import KBinsDiscretizer
df2 = pd.DataFrame({
    "Age":[22,25,30,35,40,45,50]
})
print(df2)

   Age
0   22
1   25
2   30
3   35
4   40
5   45
6   50

In [ ]:
kbd = KBinsDiscretizer(n_bins=3,encode="ordinal",strategy="uniform")
df2["Age_binned"] = kbd.fit_transform(df2[["Age"]])

0    0.0
1    0.0
2    0.0
3    1.0
4    1.0
5    2.0
6    2.0
Name: Age_binned, dtype: float64

In [21]:
df2

   Age  Age_binned
0   22         0.0
1   25         0.0
2   30         0.0
3   35         1.0
4   40         1.0
5   45         2.0
6   50         2.0